---
spring.profiles: prod

domain.sordar.internal: https://ccpri-store.syrup.co.kr
domain.syrupfriends.api: https://skp.pointda.com
syrupfriends.api.key: 8wKykFdqc4mRgESA
sms.test.domain: https://sk.planet.com/eventMeta.do
web.event.domain: playar.syrup.co.kr
future.sense.api.host: https://api.dev.knx.exchange/v1/nft/klaytn
future.sense.api.access.key: 496689CAB5D9D7D1
future.sense.api.secret.key: noD1M1VugljENO4I*+C=
nft.contract.address: '0x0cc28502567a27613ef4db4f2d7dacec92487fbd'
nft.webhook.url: https://playardev.syrup.co.kr/api/v1/web-event-front/nft/klaytn/webhook
sms.send.number: '0261190114'
encryption.use.yn: Y
domain.sodar.ia.admin: https://ccpri-sodaradmin.syrup.co.kr
domain.sodar.ma.admin: https://ccpri-sodar.syrup.co.kr

#위치기반 조회를 위한 정보
bsm:
  search:
    domain: https://ccpri-bsmsapi.syrup.co.kr
    uri: /v1/proximity/event-search
    absolute:
      uri: /v1/proximity/absolute-search
  auth:
    key: DpawBxtxjPlpYXtLVgei3d6djiaDRqG8

#기프티콘 발송 api
gifticon:
  domain: https://lsend.gifticon.com

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.22.209.190:3306/wevt?autoReconnect=true&rewriteBatchedStatements=true
    username: 'wevtadm'
    password: '!wev.Sfven9#'
    hikari:
      jdbcUrl: jdbc:mysql://172.22.209.190:3306/wevt?autoReconnect=true&rewriteBatchedStatements=true
      poolName: HikariCP
      maximumPoolSize: 750
      minimumIdle: 750
      
      idleTimeout: 356000
      maxLifetime: 357000
      connectionTimeout: 10000
      leakDetectionThreshold: 600000

  jpa:
    #hibernate:
    #      ddl-auto: update
    #      format_sql: true
    #    show-sql: false
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20000
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        generate-ddl: true
        show_sql: false
  sql:
    init:
      mode: always
      data-locations: classpath*:initdata/data-mysql.sql

management:
  security:
    enabled: false
  context-path: /api/actuator

xtrans:
  sftp:
    event-id: PlayAR
    host: 10.40.128.131
    user: aruser
    pass: apiuser1!
    port: 22
    default-path: /apps/API_DATA/PlayAR

#OK캐시백 API통신 키값 정의
ocb:
  session:
    token:
      siteid: 11302
      sid: 7cfcd0dfffb1557d
      salt: 9f07a9a249daa748
      api:
        url: https://pri-imsg.okcashbag.com/sugar/internal/session/info/partner
  point:
    api:
      url: https://pri-imsg.okcashbag.com/sugar/internal/point/save/partner

picaso:
  syrup:
    api:
      url: https://pri-picaso.syrup.co.kr/apis/v2/coupon

---
required.permission.permitList:
  ips: 172.22.202.57,172.22.202.58,172.22.202.63,172.22.202.64,172.22.202.69,172.22.202.70,10.211.104.144

aes.keyvalue:

spring:
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB